### ISSUE TITLE
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by monkey-clever** [LL1399361154/Safe-FL#1]
运行代码出现这个情况是怎么回事啊
`listening-----------cloud
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54188)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:/Users/Administrator/Desktop/Safe-FL-main/src/Cloud/cloud_server.py", line 46, in handle
    tmp = self.request.recv(1024).decode('utf-8')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
----------------------------------------`

**Comment by LL1399361154** [comment]
忘记了，这很多年前的事情了。
就是简单的socket编程，自己调试一下吧。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LL1399361154/Safe-FL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月17日(星期五) 下午4:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LL1399361154/Safe-FL] ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。 (Issue #1)





 
运行代码出现这个情况是怎么回事啊
 `listening-----------cloud
 
Exception happened during processing of request from ('127.0.0.1', 54188)
 Traceback (most recent call last):
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 650, in process_request_thread
 self.finish_request(request, client_address)
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
 self.RequestHandlerClass(request, client_address, self)
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in init
 self.handle()
 File "C:/Users/Administrator/Desktop/Safe-FL-main/src/Cloud/cloud_server.py", line 46, in handle
 tmp = self.request.recv(1024).decode('utf-8')
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1226, in recv
 return self.read(buflen)
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1101, in read
 return self._sslobj.read(len)
 ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
 ----------------------------------------`

**Comment by monkey-clever** [comment]
ssl.py 这个文件是系统下载的啊 ，我开了同一个边缘服务器的两个终端，边缘服务器上会有数据，但是云服务器上就显示直接中断了一个连接，云服务器这里没办法计算啊
